# flutter_distributor AppImage config.
display_name: FireRaccoon
icon: packaging/linux/icon_256.png
keywords:
  - Finance
  - Budget
  - Firefly
generic_name: Personal finance
categories:
  - Office
  - Finance
supported_mime_type: []
