import 'dart:math';
import 'package:flutter/material.dart';
import '../l10n/l10n_extensions.dart';
import '../theme/app_theme.dart';
import 'autocomplete_text_field.dart';
import 'tooltip_helpers.dart';

/// A list of 500 fun English words used for delete-confirmation challenges.
const List<String> _funWords = [
  'banana',
  'penguin',
  'tornado',
  'wizard',
  'pancake',
  'llama',
  'narwhal',
  'waffle',
  'disco',
  'flamingo',
  'taco',
  'unicorn',
  'pirate',
  'ninja',
  'robot',
  'pickle',
  'doodle',
  'zigzag',
  'muffin',
  'gizmo',
  'boogie',
  'kaboom',
  'snorkel',
  'pretzel',
  'yeti',
  'goblin',
  'cactus',
  'noodle',
  'wombat',
  'biscuit',
  'nugget',
  'jelly',
  'coconut',
  'bubble',
  'crumble',
  'donut',
  'fizz',
  'gadget',
  'hamster',
  'igloo',
  'juggle',
  'ketchup',
  'lemon',
  'marshmallow',
  'noodle',
  'octopus',
  'parrot',
  'quack',
  'raccoon',
  'sushi',
  'trampoline',
  'ukulele',
  'volcano',
  'walrus',
  'xylophone',
  'yogurt',
  'zeppelin',
  'avocado',
  'badger',
  'chipmunk',
  'dragonfly',
  'espresso',
  'fudge',
  'giraffe',
  'hedgehog',
  'icicle',
  'jackpot',
  'koala',
  'lobster',
  'mongoose',
  'nachos',
  'otter',
  'puffin',
  'quokka',
  'rhubarb',
  'starfish',
  'toucan',
  'umbrella',
  'voodoo',
  'whisker',
  'xeriscape',
  'yodel',
  'zephyr',
  'acrobat',
  'bongo',
  'confetti',
  'dynamite',
  'elastic',
  'frisbee',
  'gondola',
  'hooligan',
  'inkblot',
  'jamboree',
  'kazoo',
  'limbo',
  'mustache',
  'nougat',
  'origami',
  'platypus',
  'quicksand',
  'rascal',
  'spatula',
  'tadpole',
  'uproar',
  'vanilla',
  'wiggle',
  'xenon',
  'yakuza',
  'zinger',
  'armadillo',
  'bamboo',
  'crouton',
  'domino',
  'emoji',
  'falafel',
  'gnome',
  'hippo',
  'impala',
  'jellyfish',
  'kumquat',
  'leopard',
  'macaroni',
  'nutmeg',
  'omelette',
  'papaya',
  'quinoa',
  'radish',
  'sardine',
  'truffle',
  'urchin',
  'velvet',
  'weasel',
  'xerox',
  'yawn',
  'zipline',
  'alpaca',
  'burrito',
  'chameleon',
  'daffodil',
  'eclipse',
  'fossil',
  'gazelle',
  'harpoon',
  'iguana',
  'juniper',
  'kiwi',
  'lemur',
  'mango',
  'nebula',
  'opossum',
  'porcupine',
  'quartz',
  'raspberry',
  'sloth',
  'tangerine',
  'unicycle',
  'vulture',
  'woodpecker',
  'xanadu',
  'yak',
  'zucchini',
  'anchovy',
  'blizzard',
  'churro',
  'dolphin',
  'enchilada',
  'firefly',
  'gargoyle',
  'hibiscus',
  'ivory',
  'jalapeno',
  'kangaroo',
  'linguine',
  'moose',
  'nectarine',
  'oyster',
  'peacock',
  'quilted',
  'rooster',
  'salamander',
  'turnip',
  'utopia',
  'viking',
  'wasp',
  'xmas',
  'yoyo',
  'zombie',
  'alchemy',
  'baguette',
  'croissant',
  'dewdrop',
  'emerald',
  'fiesta',
  'glitter',
  'hammock',
  'illusion',
  'jackrabbit',
  'kettle',
  'lollipop',
  'mammoth',
  'napkin',
  'orchid',
  'pineapple',
  'quiche',
  'riddle',
  'sasquatch',
  'thistle',
  'upside',
  'vintage',
  'whirlpool',
  'xray',
  'yachtsman',
  'zenith',
  'asteroid',
  'buffalo',
  'caterpillar',
  'dandelion',
  'enchanted',
  'frostbite',
  'gazpacho',
  'hologram',
  'indigo',
  'jackfruit',
  'kaleidoscope',
  'labyrinth',
  'mandarin',
  'nostalgia',
  'obsidian',
  'panther',
  'quicksilver',
  'rhinoceros',
  'sapphire',
  'telescope',
  'umbrello',
  'vortex',
  'wolverine',
  'xylitol',
  'yearbook',
  'zodiac',
  'acorn',
  'bonfire',
  'cranberry',
  'drumstick',
  'elixir',
  'flamenco',
  'grizzly',
  'hurricane',
  'inferno',
  'jukebox',
  'kerfuffle',
  'licorice',
  'maelstrom',
  'nuggets',
  'obelisk',
  'paprika',
  'quasar',
  'rickshaw',
  'seashell',
  'tarantula',
  'unibrow',
  'vendetta',
  'windmill',
  'xistence',
  'yardstick',
  'zapper',
  'abracadabra',
  'butterscotch',
  'cantaloupe',
  'dingleberry',
  'eucalyptus',
  'flambe',
  'guacamole',
  'huckleberry',
  'invertebrate',
  'jackknife',
  'kilowatt',
  'lumberjack',
  'marmalade',
  'nighthawk',
  'orangutan',
  'persimmon',
  'quarterback',
  'rattlesnake',
  'snapdragon',
  'tumbleweed',
  'underdog',
  'vagabond',
  'whippoorwill',
  'xtraordinary',
  'yachtclub',
  'zillionaire',
  'accordion',
  'bellhop',
  'catapult',
  'dragonball',
  'eggnog',
  'fiddlestick',
  'garbanzo',
  'hornswoggle',
  'iguanodon',
  'jitterbug',
  'kumquat',
  'lumbago',
  'milkshake',
  'nightingale',
  'overkill',
  'pepperoni',
  'quickstep',
  'rollercoaster',
  'somersault',
  'thunderbolt',
  'uppercut',
  'ventriloquist',
  'wheelbarrow',
  'xebec',
  'yellowjacket',
  'zookeeper',
  'applesauce',
  'barnacle',
  'catfish',
  'drizzle',
  'eyelash',
  'footprint',
  'grasshopper',
  'honeybee',
  'icebreaker',
  'jellybean',
  'kickstand',
  'ladybug',
  'moonshine',
  'newsletter',
  'outlaw',
  'pinwheel',
  'quicksand',
  'rainstorm',
  'scarecrow',
  'thumbtack',
  'uptown',
  'vineyard',
  'watermelon',
  'xylograph',
  'yearling',
  'zamboni',
  'artichoke',
  'butterbean',
  'cinnamon',
  'dumplings',
  'eggplant',
  'flapjack',
  'gumdrop',
  'hotdog',
  'icecream',
  'jambalaya',
  'knapsack',
  'lemonade',
  'mushroom',
  'nutcracker',
  'oatmeal',
  'popcorn',
  'raspberry',
  'sunflower',
  'teaspoon',
  'umbrella',
  'vermicelli',
  'wafflemaker',
  'xylem',
  'yarrow',
  'zinnia',
  'artisan',
  'blueberry',
  'cantankerous',
  'dinglebell',
  'enchilada',
  'fiddler',
  'gingerbread',
  'hazelnut',
  'inkwell',
  'jawbreaker',
  'kettledrum',
  'limelight',
  'moonbeam',
  'nightcap',
  'overcoat',
  'peppermint',
  'quickfire',
  'ridgepole',
  'snowflake',
  'tinfoil',
  'upholster',
  'vineyard',
  'windchime',
  'xanthous',
  'yearlong',
  'ziggurat',
  'asteroid',
  'beeswax',
  'cornucopia',
  'dinglehopper',
  'elfin',
  'foxglove',
  'gazebo',
  'horseshoe',
  'iguanodon',
  'jellyroll',
  'kingfisher',
  'ladyfinger',
  'moonstone',
  'nutshell',
  'oakmoss',
  'pistachio',
  'quesadilla',
  'rosemary',
  'starlight',
  'tadpole',
  'umpteen',
  'vanilla',
  'whimsical',
  'xylocarp',
  'yodeler',
  'zigzaggy',
  'applewood',
  'butterfingers',
  'cupcake',
  'dandelion',
  'espresso',
  'fishstick',
  'grumble',
  'hopscotch',
  'igloo',
  'jumbalaya',
  'kickball',
  'lollygag',
  'moonwalk',
  'nuthouse',
  'overboard',
  'poppycock',
  'quickdraw',
  'razzmatazz',
  'shenanigan',
  'ticklish',
  'upswing',
  'vivacious',
  'whatchamacallit',
  'xenophile',
  'yesteryear',
  'zippydoo',
  'bandicoot',
  'chipmunk',
  'doodlebug',
  'extravaganza',
  'funicular',
  'gobbledygook',
  'hullabaloo',
  'incognito',
  'jabberwocky',
  'kerfluffle',
  'lollipop',
  'monkeyshine',
  'noodlehead',
  'oomph',
  'pizzazz',
  'quagmire',
  'rumpus',
  'skedaddle',
  'tomfoolery',
  'umami',
  'vivaldi',
  'whodunit',
  'xenomania',
  'yeehaw',
  'zigzagger',
  'bamboozle',
  'cattywampus',
  'discombobulate',
  'extravagant',
  'flibbertigibbet',
  'gobsmacked',
  'hooligan',
  'imbroglio',
  'jigglyfluff',
];

/// Shows a confirmation dialog that requires typing a fun word to confirm.
///
/// Returns `true` if confirmed, `false`/`null` if cancelled.
///
/// - [title]: Dialog title (e.g. "Delete Budget")
/// - [message]: The message body (e.g. "Are you sure you want to delete this budget?")
/// - [confirmLabel]: Label for the confirm button (e.g. "Delete")
/// - [confirmColor]: Optional color for the confirm button. Defaults to danger color.
Future<bool?> showConfirmationDialog({
  required BuildContext context,
  required String title,
  required String message,
  String confirmLabel = 'Delete',
  Color? confirmColor,
}) {
  final word = _funWords[Random().nextInt(_funWords.length)];

  return showDialog<bool>(
    context: context,
    barrierDismissible: true,
    builder: (ctx) => _ConfirmationDialog(
      title: title,
      message: message,
      confirmLabel: confirmLabel,
      confirmColor: confirmColor,
      challengeWord: word,
    ),
  );
}

class _ConfirmationDialog extends StatefulWidget {
  final String title;
  final String message;
  final String confirmLabel;
  final Color? confirmColor;
  final String challengeWord;

  const _ConfirmationDialog({
    required this.title,
    required this.message,
    required this.confirmLabel,
    this.confirmColor,
    required this.challengeWord,
  });

  @override
  State<_ConfirmationDialog> createState() => _ConfirmationDialogState();
}

class _ConfirmationDialogState extends State<_ConfirmationDialog>
    with SingleTickerProviderStateMixin {
  final _controller = TextEditingController();
  bool _isMatch = false;
  late AnimationController _animController;
  late Animation<double> _scaleAnim;

  @override
  void initState() {
    super.initState();
    _animController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 250),
    );
    _scaleAnim = CurvedAnimation(
      parent: _animController,
      curve: Curves.easeOutBack,
    );
    _animController.forward();

    _controller.addListener(() {
      final match =
          _controller.text.trim().toLowerCase() ==
          widget.challengeWord.toLowerCase();
      if (match != _isMatch) {
        setState(() => _isMatch = match);
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    _animController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;
    final l10n = context.l10n;
    final dangerColor = widget.confirmColor ?? colors.danger;

    return ScaleTransition(
      scale: _scaleAnim,
      child: Dialog(
        backgroundColor: colors.surface,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20),
          side: BorderSide(color: colors.border),
        ),
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 440),
          child: Padding(
            padding: const EdgeInsets.all(28),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Header row with icon
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(10),
                      decoration: BoxDecoration(
                        color: dangerColor.withValues(alpha: 0.12),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Icon(
                        Icons.warning_amber_rounded,
                        color: dangerColor,
                        size: 22,
                      ),
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Text(
                        widget.title,
                        style: context.textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 20),

                // Message
                Text(
                  widget.message,
                  style: TextStyle(
                    color: colors.text2,
                    fontSize: 14,
                    height: 1.5,
                  ),
                ),
                const SizedBox(height: 20),

                // Challenge instruction
                RichText(
                  text: TextSpan(
                    style: TextStyle(
                      fontFamily: 'Comfortaa',
                      color: colors.text2,
                      fontSize: 13,
                      height: 1.5,
                    ),
                    children: [
                      TextSpan(text: l10n.confirmTypeWord),
                      TextSpan(
                        text: widget.challengeWord,
                        style: TextStyle(
                          fontWeight: FontWeight.w800,
                          color: dangerColor,
                          letterSpacing: 0.5,
                        ),
                      ),
                      TextSpan(text: l10n.confirmToConfirm),
                    ],
                  ),
                ),
                const SizedBox(height: 10),

                // Input field
                withTooltip(
                  l10n.tooltipConfirmChallenge,
                  AutocompleteTextField(
                    controller: _controller,
                    autofocus: true,
                    showOnFocus: false,
                    hideOnEmpty: true,
                    suggestions: [widget.challengeWord],
                    style: TextStyle(
                      fontFamily: 'Comfortaa',
                      color: colors.text,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                    ),
                    decoration: InputDecoration(
                      hintText: l10n.confirmHint,
                      hintStyle: TextStyle(
                        color: colors.text3,
                        fontWeight: FontWeight.w400,
                      ),
                      filled: true,
                      fillColor: colors.surface2,
                      contentPadding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 14,
                      ),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide(color: colors.border),
                      ),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide(color: colors.border),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                        borderSide: BorderSide(
                          color: _isMatch ? dangerColor : colors.accent.acc,
                          width: 2,
                        ),
                      ),
                      suffixIcon: _isMatch
                          ? Icon(
                              Icons.check_circle,
                              color: dangerColor,
                              size: 20,
                            )
                          : null,
                    ),
                    onSubmitted: (_) {
                      if (_isMatch) Navigator.of(context).pop(true);
                    },
                  ),
                ),
                const SizedBox(height: 24),

                // Action buttons
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    withTooltip(
                      l10n.tooltipCancel,
                      TextButton(
                        onPressed: () => Navigator.of(context).pop(false),
                        style: TextButton.styleFrom(
                          foregroundColor: colors.text2,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 20,
                            vertical: 12,
                          ),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                        child: Text(l10n.cancel),
                      ),
                    ),
                    const SizedBox(width: 10),
                    AnimatedOpacity(
                      opacity: _isMatch ? 1.0 : 0.4,
                      duration: const Duration(milliseconds: 200),
                      child: withTooltip(
                        l10n.tooltipConfirmDelete,
                        ElevatedButton(
                          onPressed: _isMatch
                              ? () => Navigator.of(context).pop(true)
                              : null,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: dangerColor,
                            foregroundColor: Colors.white,
                            disabledBackgroundColor: dangerColor.withValues(
                              alpha: 0.3,
                            ),
                            disabledForegroundColor: Colors.white54,
                            padding: const EdgeInsets.symmetric(
                              horizontal: 24,
                              vertical: 12,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                          child: Text(widget.confirmLabel),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
